### ISSUE TITLE
Youtube search broken

### ISSUE THREAD

**Issue by minhtuan30306** [TheDiscorders/SelfRythm#29]
**Describe the bug**
Youtube.search boken

**To Reproduce**
$play [search]

**Expected behavior**
Play Music

**Screenshots**
/home/username/SelfRythm/utils.js:62
            YouTube.search(stringOfWords, { limit: 1 })
                    ^

TypeError: YouTube.search is not a function
    at /home/username/SelfRythm/utils.js:62:21
    at new Promise (<anonymous>)
    at Object.getUrl (/home/username/SelfRythm/utils.js:61:24)
    at Object.module.exports.run (/home/username/SelfRythm/commands/play.js:24:28)
    at module.exports (/home/username/SelfRythm/events/message.js:13:13)
    at Client.emit (node:events:365:28)
    at MessageCreateAction.handle (/home/username/SelfRythm/node_modules/discord.js-selfbot/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/username/SelfRythm/node_modules/discord.js-selfbot/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/username/SelfRythm/node_modules/discord.js-selfbot/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/username/SelfRythm/node_modules/discord.js-selfbot/src/client/websocket/WebSocketShard.js:435:22)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Lastest
 - Node Version: any

**Additional context**
You fogot .default at const YouTube = require("youtube-sr"); in utils.js

**Comment by Firokat** [comment]
In fact, this changed in recent versions of youtube-dl. Going to fix that today. Thanks for feedback

**Comment by Firokat** [comment]
Issue should be fixed now, it was already fixed on the Docker branch but wasn't merged to main.
