### ISSUE TITLE
bug ffmpeg please help

### ISSUE THREAD

**Issue by pengengantibaju** [TheDiscorders/SelfRythm#45]
(node:43668) UnhandledPromiseRejectionWarning: Error: FFmpeg/avconv not found!
    at Function.getInfo (/root/self/node_modules/prism-media/src/core/FFmpeg.js:143:11)
    at Function.create (/root/self/node_modules/prism-media/src/core/FFmpeg.js:156:38)
    at new FFmpeg (/root/self/node_modules/prism-media/src/core/FFmpeg.js:45:27)
    at AudioPlayer.playUnknown (/root/self/node_modules/discord.js-selfbot/src/client/voice/player/BasePlayer.js:47:20)
    at VoiceConnection.play (/root/self/node_modules/discord.js-selfbot/src/client/voice/util/PlayInterface.js:71:28)
    at Object.play (/root/self/utils.js:83:51)
    at Object.module.exports.run (/root/self/commands/play.js:63:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:43668) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Firokat** [comment]
Have you installed FFMPEG ? Is it in your PATH ?
